### ISSUE TITLE
TS compiler errors from loaders.gl

### ISSUE THREAD

**Issue by spelman7** [nytimes/three-loader-3dtiles#12]
This library is great, but at the moment I can't use it without significantly changing my Typescript build flags because of config issues with the `loaders.gl` library. [This issue documents it well](https://github.com/visgl/loaders.gl/issues/1828). 

It seems like the `loaders.gl` team has been hard at work fixing the issue in version 3.1 of the library, so I'm just leaving a note here requesting that `three-loader-3dtiles` use the 3.1.X version of `loaders.gl` as soon as it's ready. Thanks!

**Comment by Avnerus** [comment]
Hi! Thank you for this issue.
When this library was first written I also dealt with several Typescript compiler errors and warnings in loaders.gl and we were able to solve them toward the 3.0 release. However, it is likely that I did not have all flags enabled, such as the `noImplicityAny` flag mentioned in that issue. 
That is great to hear they are resolving this in 3.1, will definitely migrate as soon as it's released. Feel free to bump this issue when that happens if you notice before I do. 
Thanks again!
/Avner

**Comment by Avnerus** [comment]
Started migration but stumbled into a console error. Opened an [issue at loaders.gl](https://github.com/visgl/loaders.gl/issues/2014).

**Comment by Avnerus** [comment]
@spelman7 A new version which uses loaders.gl 3.1.4 is now published. Let me know if it solves your issue?

**Comment by spelman7** [comment]
@Avnerus - nice!! Thanks so much, I'll take it for a spin today.

**Comment by spelman7** [comment]
@Avnerus - yep, totally passes the build tests now. Thanks so much for your work in addressing this - I'll close the issue now.
